# Generated by Django 5.1.4 on 2025-01-02 16:56

import planner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='end_date',
            field=models.DateField(default=planner.models.get_current_week_end),
        ),
        migrations.AlterField(
            model_name='week',
            name='start_date',
            field=models.DateField(default=planner.models.get_current_week_start),
        ),
    ]
